create table file (
	id int8 generated by default as identity,
	institution_id int4,
	institution_hash varchar(100),
	artifact_id int4,
	artifact_hash varchar(100),
	extension varchar(100),
	primary key (id)
);